//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShawarmaEntities : DbContext
    {
        public ShawarmaEntities()
            : base("name=ShawarmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingradient> Ingradients { get; set; }
        public virtual DbSet<IngradientCategory> IngradientCategories { get; set; }
        public virtual DbSet<OrderHeader> OrderHeaders { get; set; }
        public virtual DbSet<PriceController> PriceControllers { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<SellingPoint> SellingPoints { get; set; }
        public virtual DbSet<Shawarma> Shawarmas { get; set; }
        public virtual DbSet<ShawarmaRecipeId> ShawarmaRecipeIds { get; set; }
        public virtual DbSet<TimeController> TimeControllers { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
    }
}
